name: Build Ramdisk

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential git wget

    - name: Build Ramdisk
      run: |
        git clone https://github.com/droidian/droidian-build.git
        cd droidian-build
        ./build-ramdisk.sh generic
